# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: gcloud sdkをインストール
  shell: "{{ home }}/google-cloud-sdk/install.sh --command-completion true --path-update true --quiet"
