- name: brew経由のインストール
  block:
    - name: brewで最低限必要なものをインストール
      homebrew:
        name:
          - git
          - wget
          - curl
          - gnu-tar
        update_homebrew: true

- name: brew cask経由のインストール
  block:
    - name: brewで最低限必要なものをインストール
      homebrew_cask:
        name:
          - google-chrome
          - docker
        state: present
