- name: brew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - homebrew/core
    - homebrew/cask
    - homebrew/cask-versions

- name: brewで最低限必要なものをインストール
  homebrew:
    name:
      - git
      - wget
      - curl
      - gnu-tar
    update_homebrew: true

- name: brew caskで最低限必要なものをインストール
  homebrew_cask:
    name:
      - docker
      - google-chrome
    state: present
    ignore_errors: yes
    install_options:
      - force
