- name: brew経由のインストール
  block:
    - name: brewで最低限必要なものをインストール
      homebrew:
        name:
          - google-chrome
          - docker
          - git
          - wget
          - curl
          - gnu-tar
        ignore_errors: true
        update_homebrew: true
