- name: brew経由のインストール
  block:
    - name: brewで最低限必要なものをインストール
      homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      loop:
        - git
        - wget
        - curl
        - gnu-tar

- name: brew cask経由のインストール
  homebrew:
    name: docker
