- name: brew経由のインストール
  block:
    - name: brewをupdate
      homebrew:
        update_homebrew: yes

    - name: brewで最低限必要なものをインストール
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - wget
        - curl
        - gnu-tar

- name: brew cask経由のインストール
  homebrew:
    homebrew_cask:
      name: "{{ item }}"
  loop:
    - docker
    - google-chrome
