- name: brew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - homebrew/core
    - homebrew/cask
    - homebrew/cask-versions

- name: brew update
  homebrew:
    update_homebrew: true
- name: brewで最低限必要なものをインストール
  homebrew:
    name: "{{ item }}"
  loop: "{{ brew_install_apps }}"

- name: brew caskで最低限必要なものをインストール
  homebrew_cask:
    name: "{{ item }}"
  #CI上でインストールに失敗するのでエラーを無視
  ignore_errors: true
  loop: "{{ brew_cask_install_apps }}"
