- name: repository追加に必要なツールをインストール
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: apt keyを追加
  become: true
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  loop: "{{ apt_add_keys }}"

- shell: lsb_release -cs
  ignore_errors: true
  register: lsb_release
  no_log: true

- name: dockerのapt repositoryを追加
  become: true
  apt_repository:
    update_cache: true
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  loop: "{{ apt_add_repositories }}"

- name: aptのcacheアップデート
  become: true
  update_cache: true

- name: aptで最低限必要なものをインストール
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt_install_apps }}"
