# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-update_cache
- name: aptのcacheアップデート
  become: true
  apt:
    update_cache: true

# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: repository追加に必要なツールをインストール
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
- name: apt keyを追加
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ apt.add_keys }}"

# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
- name: dockerのapt repositoryを追加
  become: true
  apt_repository:
    update_cache: true
    repo: "{{ item }}"
    state: present
  loop: "{{ apt.add_repositories }}"

# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-update_cache
- name: aptのcacheアップデート
  become: true
  apt:
    update_cache: true

# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: aptで最低限必要なものをインストール
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt.install_apps }}"

- name: rootless dockerをインストール
  shell:
    cmd: curl -fsSL https://get.docker.com/rootless | sh
    warn: false
