- name: repository追加に必要なツールをインストール
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: apt keyを追加
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ apt.add_keys }}"

- name: dockerのapt repositoryを追加
  become: true
  apt_repository:
    update_cache: true
    repo: "{{ item }}"
    state: present
  loop: "{{ apt.add_repositories }}"

- name: aptのcacheアップデート
  become: true
  apt:
    update_cache: true

- name: aptで最低限必要なものをインストール
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt.install_apps }}"
