- name: gcloudインストール確認
  shell: command -v gcloud 2>&1
  register: gcloud_install
  failed_when: false
  changed_when: false

- name: gcloudをインストール
  vars:
    gcloud_sdk_version: 319.0.0
  block:
    - shell: mktemp -u
      register: temp_file_name

    - name: gcloud sdkをダウンロード
      get_url: url={{ gcloud.download_url }} dest={{ temp_file_name.stdout }}

    - name: gcloud sdkを解凍
      unarchive:
        src: "{{ temp_file_name.stdout }}"
        dest: "{{ home }}"

    - name: gcloudコンポーネントアップデートを実行
      shell: "{{ home }}/google-cloud-sdk/bin/gcloud components update --quiet"
  when:
    - gcloud_install.stdout == "" or force_install == "true"
