# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: Ubuntuのバージョン取得
  shell: lsb_release -cs
  ignore_errors: true
  register: lsb_release
  changed_when: false
