# google cloud sdkのバージョン
gcloud_sdk_version: 319.0.0

# asdfで使用するプラグイン
# Document https://github.com/cimon-io/ansible-role-asdf#ansible-asdf-role
asdf_plugins:
  - name: "terraform"
    versions:
      - "0.14.2"
  - name: "nodejs"
  - name: "rust"
  - name: "golang"

pip:
  install_apps:
    - pre-commit
    - ansible-lint
