- name: dockerインストール確認
  shell: command -v docker 2>&1
  ignore_errors: true
  register: docker_install

- name: dockerをインストール
  block:
    - include_tasks: ubuntu.yaml
      when:
        - ansible_distribution == "Ubuntu"
    - include_tasks: mac.yaml
      when:
        - ansible_distribution == "MacOSX"
  when:
    - docker_install.stdout == ""
