- name: dockerをインストール
  block:
    - include_tasks: ubuntu.yaml
      when:
        - ansible_distribution == "Ubuntu"
    - include_tasks: mac.yaml
      when:
        - ansible_distribution == "MacOSX"
