- name: 基本ツールをインストール
  include_tasks: tasks/install/basic/basic.yaml
- name: dockerをインストール
  include_tasks: tasks/install/docker/docker.yaml
- name: gcloudをインストール
  include_tasks: tasks/install/gcloud/gcloud.yaml
