- block:
    - name: 事前処理
      include_tasks: tasks/install/prepare/prepare.yaml
    - name: 設定読込
      include_vars:
        file: "vars/install/setting/setting.yaml"
    - name: 環境ごとの設定読込
      include_vars:
        file: "vars/install/setting/{{ ansible_distribution }}.yaml"
    - name: 基本ツールをインストール
      include_tasks: tasks/install/basic/basic.yaml
    - name: gcloudをインストール
      include_tasks: tasks/install/gcloud/gcloud.yaml
