- include_vars:
    file: "install/setting.{{ ansible_distribution }}.yaml"
  block:
    - name: 基本ツールをインストール
      include_tasks: tasks/install/basic/basic.yaml
    - name: gcloudをインストール
      include_tasks: tasks/install/gcloud/gcloud.yaml
