- block:
    - include_vars:
        file: "vars/install/setting.{{ ansible_distribution }}.yaml"
    - name: 基本ツールをインストール
      include_tasks: tasks/install/basic/basic.yaml
    - name: gcloudをインストール
      include_tasks: tasks/install/gcloud/gcloud.yaml
