- hosts: localhost
  vars:
    home: "$HOME"
  tasks:
    - include_tasks: install.yaml
    - include_tasks: config.yaml
      when:
        - set_config == true
  roles:
    - role: markosamuli.asdf
      asdf_init_shell: "{{ set_config }}"
