- hosts: localhost
  vars:
    home: "$HOME"
  tasks:
    - name: 必要なツールをインストール
      include_tasks: install.yaml
    - name: コンフィグの設定
      include_tasks: config.yaml
      when:
        - set_config == "true"
  roles:
    - role: markosamuli.asdf
      asdf_init_shell: "{{ set_config }}"
      asdf_plugins:
        - name: "terraform"
          global: "0.14.2"
