# Document https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: rootless dockerの設定追加
  vars:
    start: "# BEGIN_DOCKER_CONFIG"
    end: "# END_DOCKER_CONFIG"
    script: "export DOCKER_HOST=unix:///run/user/1000/docker.sock"
  shell: >-
    cat {{ home }}/.profile | grep -Pzo "{{ start }}[\s\S]*{{ end }}" || bash -c "echo -e \"\n{{ start }}\n{{ script }}\n{{ end }}\n\"" >> {{ home }}/.profile
