- name: docker group作成
  become: true
  ignore_errors: true
  shell: groupadd docker

- name: get the username running the deploy
  become: false
  shell: whoami
  register: username_on_the_host

- name: 現行ユーザをdockerグループに所属させる
  become: true
  shell: "gpasswd -a {{ username_on_the_host.stdout }} docker"
