- name: 環境に依存するツールをインストール
  block:
    - include_tasks: ubuntu.yaml
      when:
        - ansible_distribution == "Ubuntu"
    - include_tasks: mac.yaml
      when:
        - ansible_distribution == "MacOSX"
