- name: apt経由のインストール
  block:
    - name: aptで最低限必要なものをインストール
      become: true
      apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - git
        - wget
        - curl
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common

    - name: dockerのapt keyを追加
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: lsb_releaseを宣言
      shell: lsb_release -cs
      ignore_errors: true
      register: lsb_release

    - name: dockerのapt repositoryを追加
      become: true
      apt_repository:
        update_cache: true
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
        state: present

    - name: docker-ceをインストール
      become: true
      apt:
        name: docker-ce
        state: present
        update_cache: true
