- name: apt経由のインストール
  block:
    - name: aptで最低限必要なものをインストール
      become: true
      apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - git
        - wget
        - curl
