- apt_install_apps:
    - git
    - wget
    - curl
    - tar
    - docker-ce
    - google-chrome-stable

- apt_add_keys:
    - url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    - url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present

- apt_add_repositories:
    - repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
      state: present
    - repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
      state: present
