name: Ansible Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./ansible/setup.yaml"
