name: install_test
on: [push, pull_request]
jobs:
  install_test_shell:
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: mxschmitt/action-tmate@v3
